services:
  postgres:
      image: postgres:15
      container_name: postgres
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: mydb
      ports:
        - "5431:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
